### ISSUE TITLE
CMStore's saveUserObject does not check if theObject is nil

### ISSUE THREAD

**Issue by BenSS** [cloudmine/CloudMineSDK-iOS#72]
The SDK should not crash if the app happens to attempt save on a nil object.

**Comment by apbendi** [comment]
hey @BenSS, agree it ought not crash. What would you expect the behavior to be with regards to the callback? 

 1. No-op and callback is never executed -OR-
 2. Callback is executed with an error response

**Comment by BenSS** [comment]
Tough choice! I can think of situations where both would be appropriate. I am leaning towards the first as a no-op since it's more likely you never intended to try and save a nil object.
