### ISSUE TITLE
App Crashing after sign in with CloudMine custom user class after upgrading to 1.7.11 

### ISSUE THREAD

**Issue by a4arpan** [cloudmine/CloudMineSDK-iOS#81]
App Crashing after sign in with CloudMine custom user class after upgrading to 1.7.11 	

	2016-09-26 09:11:31.012 DiscoverFood[827:640922] +[CustomCMUser rt_properties]: unrecognized selector sent to class 0x105da5b30
	2016-09-26 09:11:31.021 DiscoverFood[827:640922] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[CustomCMUser rt_properties]: unrecognized selector sent to class 0x105da5b30'
	*** First throw call stack:
	(
		0   CoreFoundation                      0x000000010692234b __exceptionPreprocess + 171
		1   libobjc.A.dylib                     0x000000010b64e21e objc_exception_throw + 48
		2   CoreFoundation                      0x0000000106991e74 +[NSObject(NSObject) doesNotRecognizeSelector:] + 132
		3   CoreFoundation                      0x00000001068a7c15 ___forwarding___ + 1013
		4   CoreFoundation                      0x00000001068a7798 _CF_forwarding_prep_0 + 120
		5   DiscoverFood                        0x0000000105c9d589 -[CMUser executeBlockForAllUserDefinedProperties:] + 105
		6   DiscoverFood                        0x0000000105c9d85d -[CMUser registerAllPropertiesForKVO] + 125
		7   DiscoverFood                        0x0000000105c9d146 -[CMUser initWithEmail:andUsername:andPassword:] + 454

	#import "CustomCMUser.h"

	@implementation CustomCMUser

	- (id)initWithCoder:(NSCoder *)aDecoder {
	    if (self = [super initWithCoder:aDecoder]) {
	        _object_id = [aDecoder decodeObjectForKey:CMInternalObjectIdKey];
	        _sessionToken = [aDecoder decodeObjectForKey:@"token"];
	        _sessionTokenExpiration = [aDecoder decodeObjectForKey:@"tokenExpiration"];
	        
	        _lastIP = [aDecoder decodeObjectForKey:@"lastIP"];
	        _lastDevice = [aDecoder decodeObjectForKey:@"lastDevice"];
	        _lastDeviceOS = [aDecoder decodeObjectForKey:@"lastDeviceOS"];
	 	}
	 	return self;
	 }

	 - (void)encodeWithCoder:(NSCoder *)aCoder {
	    [super encodeWithCoder:aCoder];
	    
	    [aCoder encodeObject:_object_id forKey:@"object_id"];
	    [aCoder encodeObject:_sessionToken forKey:@"sessionToken"];
	    [aCoder encodeObject:_sessionTokenExpiration forKey:@"sessionTokenExpiration"];
	    [aCoder encodeObject:_lastIP forKey:@"lastIP"];
	    [aCoder encodeObject:_lastDevice forKey:@"lastDevice"];
	    [aCoder encodeObject:_lastDeviceOS forKey:@"lastDeviceOS"];
	}

**Comment by a4arpan** [comment]
The same code works on 1.7.8. Please suggest whats wrong with my class?

**Comment by apbendi** [comment]
Hey @a4arpan, the error is strange. The method it can't find is a category method defined in a vendored dependency. It should be there, and my first instinct is that something is out of whack with linking or importing. Something to try:

First, ensure that your `CustomCMUser.h` file has exactly the following import statement:

```ObjC
#import <CloudMine/CloudMine.h>
```

Afterwards, perform these steps:

1. Close Xcode
2. Blow away your the CocoaPods `Pods` directory and the `Podfile.lock` file. Then run `pod install`.
3. Open the `.xcworkspace` file
4. Do a clean (cmd-shift-K) and clean your build directory (cmd-shift-ooption-k)
5. Build and run: (cmd-b)

If those steps don't resolve, let us know, and we'll take it from there.

**Comment by apbendi** [comment]
hey @a4arpan, just checking in: any luck?

**Comment by a4arpan** [comment]
Hey @apbendi 

I double checked everything as you suggested and thats already I was doing, it was failing with 1.7.12  and working on 1.7.8, but now everything works great. may be a build directory issue?

Thank you so much @apbendi closing this ticket for now.

So sorry for the delayed reply, I had to move out of town for some errand.
